export enum NotificationType {
  PET_INVITATION = 'PET_INVITATION',
  VACCINE_DUE = 'VACCINE_DUE',
  APPOINTMENT = 'APPOINTMENT',
  MEDICATION = 'MEDICATION',
  SHARED_ACCESS = 'SHARED_ACCESS',
  GENERAL = 'GENERAL',
  REMINDER = 'REMINDER',
  MEDICAL = 'MEDICAL',           // ✅ NUEVO
  VETERINARY_ALERT = 'VETERINARY_ALERT'
}